spring:
  application:
    name: planner
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/local
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect